// <auto-generated />
using System;
using DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(BlogDbContext))]
    [Migration("20240924155018_mig_1")]
    partial class mig_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Core.Models.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("adb10406-74a5-43d0-8dc4-7c7601a2be81"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aee8acaf-cf04-4698-bdb3-c6824e485c80",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 221, DateTimeKind.Local).AddTicks(6897),
                            Email = "user1@example.com",
                            EmailConfirmed = true,
                            FirstName = "John",
                            IsDeleted = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER1@EXAMPLE.COM",
                            NormalizedUserName = "USER1",
                            PasswordHash = "AQAAAAIAAYagAAAAEGxoDpw62TiB4yw/NxUny7yrX8fHAL4NJO7pQlgUy+YuctzhyxpwcSBuSaUilIjfmQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user1"
                        },
                        new
                        {
                            Id = new Guid("23cd5436-94e4-4428-bc70-d852d40e135d"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c91520e7-0916-472f-8384-01b5c04f580b",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 285, DateTimeKind.Local).AddTicks(9906),
                            Email = "user2@example.com",
                            EmailConfirmed = true,
                            FirstName = "Jane",
                            IsDeleted = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER2@EXAMPLE.COM",
                            NormalizedUserName = "USER2",
                            PasswordHash = "AQAAAAIAAYagAAAAEHS9mzWhVDWWAkscl4Vr1u1Cc1RRUsW1DP/e4kjrZb6PmO8VYEINzT49TxVE84ihMQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user2"
                        },
                        new
                        {
                            Id = new Guid("ed33ce45-691f-4fb9-b363-bf030e3bbba1"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "755feb5c-35df-4c05-ada6-45dea4ff13ae",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 352, DateTimeKind.Local).AddTicks(7072),
                            Email = "user3@example.com",
                            EmailConfirmed = true,
                            FirstName = "Mark",
                            IsDeleted = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER3@EXAMPLE.COM",
                            NormalizedUserName = "USER3",
                            PasswordHash = "AQAAAAIAAYagAAAAEJXaQg6vqEn9768aLz1bkmhpSrdRVUw0/Tw8NVfuMu31rCS+KkK5FXov9Bgpkh722w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user3"
                        },
                        new
                        {
                            Id = new Guid("e0d55b4b-b6b5-49ee-bbd7-95ae242c3391"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "0db32de0-ef7b-477f-9603-38f65dfcb204",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 426, DateTimeKind.Local).AddTicks(1051),
                            Email = "user4@example.com",
                            EmailConfirmed = true,
                            FirstName = "Hans",
                            IsDeleted = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER4@EXAMPLE.COM",
                            NormalizedUserName = "USER4",
                            PasswordHash = "AQAAAAIAAYagAAAAEE3zypLDRZOj+5YmX/xJTofktsWhRxzAxaoj4915Lrc5K3sIh0tlqXrv7AuocNgx9w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user4"
                        },
                        new
                        {
                            Id = new Guid("a4523db6-ab98-41ed-a598-11419ad168e3"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e13a370c-c72f-451a-88c9-a435ee8151e0",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 497, DateTimeKind.Local).AddTicks(3725),
                            Email = "user5@example.com",
                            EmailConfirmed = true,
                            FirstName = "Marry",
                            IsDeleted = false,
                            LastName = "Doe",
                            LockoutEnabled = false,
                            NormalizedEmail = "USER5@EXAMPLE.COM",
                            NormalizedUserName = "USER5",
                            PasswordHash = "AQAAAAIAAYagAAAAEAN5lODC/aVNAFsyh7TIFPEssccQPPmnG7WF3HswdDLLv7YiegIiM8w426N94DLiYQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "",
                            TwoFactorEnabled = false,
                            UserName = "user5"
                        });
                });

            modelBuilder.Entity("Core.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CoverImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasGallery")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppUserId = new Guid("adb10406-74a5-43d0-8dc4-7c7601a2be81"),
                            Content = "This is the content of the first article.",
                            CoverImageUrl = "https://example.com/cover1.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8090),
                            HasGallery = true,
                            IsDeleted = false,
                            IsPublished = true,
                            IsRejected = false,
                            Title = "First Article"
                        },
                        new
                        {
                            Id = 2,
                            AppUserId = new Guid("23cd5436-94e4-4428-bc70-d852d40e135d"),
                            Content = "This is the content of the second article.",
                            CoverImageUrl = "https://example.com/cover2.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8146),
                            HasGallery = false,
                            IsDeleted = false,
                            IsPublished = false,
                            IsRejected = false,
                            Title = "Second Article"
                        },
                        new
                        {
                            Id = 3,
                            AppUserId = new Guid("ed33ce45-691f-4fb9-b363-bf030e3bbba1"),
                            Content = "This is the content of the third article.",
                            CoverImageUrl = "https://example.com/cover3.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8149),
                            HasGallery = true,
                            IsDeleted = false,
                            IsPublished = true,
                            IsRejected = false,
                            Title = "Third Article"
                        },
                        new
                        {
                            Id = 4,
                            AppUserId = new Guid("e0d55b4b-b6b5-49ee-bbd7-95ae242c3391"),
                            Content = "This is the content of the fourth article.",
                            CoverImageUrl = "https://example.com/cover4.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8151),
                            HasGallery = false,
                            IsDeleted = false,
                            IsPublished = true,
                            IsRejected = false,
                            Title = "Fourth Article"
                        },
                        new
                        {
                            Id = 5,
                            AppUserId = new Guid("a4523db6-ab98-41ed-a598-11419ad168e3"),
                            Content = "This is the content of the fifth article.",
                            CoverImageUrl = "https://example.com/cover5.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8158),
                            HasGallery = true,
                            IsDeleted = false,
                            IsPublished = false,
                            IsRejected = false,
                            Title = "Fifth Article"
                        },
                        new
                        {
                            Id = 6,
                            AppUserId = new Guid("adb10406-74a5-43d0-8dc4-7c7601a2be81"),
                            Content = "This is the content of the sixth article.",
                            CoverImageUrl = "https://example.com/cover6.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8160),
                            HasGallery = false,
                            IsDeleted = false,
                            IsPublished = true,
                            IsRejected = false,
                            Title = "Sixth Article"
                        },
                        new
                        {
                            Id = 7,
                            AppUserId = new Guid("23cd5436-94e4-4428-bc70-d852d40e135d"),
                            Content = "This is the content of the seventh article.",
                            CoverImageUrl = "https://example.com/cover7.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8163),
                            HasGallery = true,
                            IsDeleted = false,
                            IsPublished = false,
                            IsRejected = false,
                            Title = "Seventh Article"
                        },
                        new
                        {
                            Id = 8,
                            AppUserId = new Guid("ed33ce45-691f-4fb9-b363-bf030e3bbba1"),
                            Content = "This is the content of the eighth article.",
                            CoverImageUrl = "https://example.com/cover8.jpg",
                            CreatedAt = new DateTime(2024, 9, 24, 18, 50, 18, 562, DateTimeKind.Local).AddTicks(8168),
                            HasGallery = false,
                            IsDeleted = false,
                            IsPublished = true,
                            IsRejected = false,
                            Title = "Eighth Article"
                        });
                });

            modelBuilder.Entity("Core.Models.ArticleCategory", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ArticleId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ArticleCategories");
                });

            modelBuilder.Entity("Core.Models.ArticleComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRejected")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleComments");
                });

            modelBuilder.Entity("Core.Models.ArticleImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AltText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleImages");
                });

            modelBuilder.Entity("Core.Models.ArticleLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LikedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleLikes");
                });

            modelBuilder.Entity("Core.Models.ArticleTag", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("TagId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("ArticleId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ArticleTags");
                });

            modelBuilder.Entity("Core.Models.ArticleView", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AppUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ViewedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppUserId");

                    b.HasIndex("ArticleId");

                    b.ToTable("ArticleViews");
                });

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            IsDeleted = false,
                            Name = "Technology"
                        },
                        new
                        {
                            CategoryId = 2,
                            IsDeleted = false,
                            Name = "Science"
                        },
                        new
                        {
                            CategoryId = 3,
                            IsDeleted = false,
                            Name = "Health"
                        });
                });

            modelBuilder.Entity("Core.Models.Tag", b =>
                {
                    b.Property<int>("TagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagId"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagId");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            TagId = 1,
                            IsDeleted = false,
                            Name = "AI"
                        },
                        new
                        {
                            TagId = 2,
                            IsDeleted = false,
                            Name = "Machine Learning"
                        },
                        new
                        {
                            TagId = 3,
                            IsDeleted = false,
                            Name = "COVID-19"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("64ec8363-9d54-498a-b3da-3aba1925b8e4"),
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = new Guid("d54d970d-dff1-49b4-bd4f-438f0b3a8bec"),
                            Name = "Author",
                            NormalizedName = "AUTHOR"
                        },
                        new
                        {
                            Id = new Guid("fc815bfa-4553-4fa5-a122-d87dd80d6fda"),
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("adb10406-74a5-43d0-8dc4-7c7601a2be81"),
                            RoleId = new Guid("64ec8363-9d54-498a-b3da-3aba1925b8e4")
                        },
                        new
                        {
                            UserId = new Guid("23cd5436-94e4-4428-bc70-d852d40e135d"),
                            RoleId = new Guid("d54d970d-dff1-49b4-bd4f-438f0b3a8bec")
                        },
                        new
                        {
                            UserId = new Guid("ed33ce45-691f-4fb9-b363-bf030e3bbba1"),
                            RoleId = new Guid("fc815bfa-4553-4fa5-a122-d87dd80d6fda")
                        },
                        new
                        {
                            UserId = new Guid("e0d55b4b-b6b5-49ee-bbd7-95ae242c3391"),
                            RoleId = new Guid("fc815bfa-4553-4fa5-a122-d87dd80d6fda")
                        },
                        new
                        {
                            UserId = new Guid("a4523db6-ab98-41ed-a598-11419ad168e3"),
                            RoleId = new Guid("fc815bfa-4553-4fa5-a122-d87dd80d6fda")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Core.Models.Article", b =>
                {
                    b.HasOne("Core.Models.AppUser", "AppUser")
                        .WithMany("Articles")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AppUser");
                });

            modelBuilder.Entity("Core.Models.ArticleCategory", b =>
                {
                    b.HasOne("Core.Models.Article", "Article")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Category", "Category")
                        .WithMany("ArticleCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Core.Models.ArticleComment", b =>
                {
                    b.HasOne("Core.Models.AppUser", "AppUser")
                        .WithMany("ArticleComments")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Article", "Article")
                        .WithMany("ArticleComments")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Core.Models.ArticleImage", b =>
                {
                    b.HasOne("Core.Models.Article", "Article")
                        .WithMany("ArticleImages")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Core.Models.ArticleLike", b =>
                {
                    b.HasOne("Core.Models.AppUser", "AppUser")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Article", "Article")
                        .WithMany("ArticleLikes")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Core.Models.ArticleTag", b =>
                {
                    b.HasOne("Core.Models.Article", "Article")
                        .WithMany("ArticleTags")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Tag", "Tag")
                        .WithMany("ArticleTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Tag");
                });

            modelBuilder.Entity("Core.Models.ArticleView", b =>
                {
                    b.HasOne("Core.Models.AppUser", "AppUser")
                        .WithMany("ArticleViews")
                        .HasForeignKey("AppUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.Article", "Article")
                        .WithMany("ArticleViews")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AppUser");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Core.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Core.Models.AppUser", b =>
                {
                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleLikes");

                    b.Navigation("ArticleViews");

                    b.Navigation("Articles");
                });

            modelBuilder.Entity("Core.Models.Article", b =>
                {
                    b.Navigation("ArticleCategories");

                    b.Navigation("ArticleComments");

                    b.Navigation("ArticleImages");

                    b.Navigation("ArticleLikes");

                    b.Navigation("ArticleTags");

                    b.Navigation("ArticleViews");
                });

            modelBuilder.Entity("Core.Models.Category", b =>
                {
                    b.Navigation("ArticleCategories");
                });

            modelBuilder.Entity("Core.Models.Tag", b =>
                {
                    b.Navigation("ArticleTags");
                });
#pragma warning restore 612, 618
        }
    }
}
